language: C

install:
  - CHANNEL=http://eupsforge.net/conda/dev ./setup/travis_install.sh lsst-sims nose pandas
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - setup lsst_sims
  - eups declare -r . Twinkles -t current
  - setup Twinkles
  - pip install future --upgrade
  - pip install pylint

cache:
  directories:
  - $HOME/miniconda.tarball

services:
  - mysql

before_script:
  - mysql -e 'create database myapp_test'
  - mysql -e 'show databases;'

script:
  - nosetests -s
  - pylint --py3k `find . -name \*.py -print`
