language: C

install:
  - travis_wait 25 ./setup/travis_install.sh lsst-sims nose pandas pylint
  - ln -sf /home/travis/miniconda/lib/libssl.so.1.0.0 /home/travis/miniconda/lib/libssl.so.10
  - ln -sf /home/travis/miniconda/lib/libcrypto.so.1.0.0 /home/travis/miniconda/lib/libcrypto.so.10
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - pip install coveralls
  - setup lsst_sims
  - eups declare -r . Twinkles -t current
  - setup twinkles

cache:
  directories:
  - $HOME/miniconda.tarball
  timeout: 600
before_cache:
  - du -h $HOME/miniconda.tarball
  - ls -l $HOME/miniconda.tarball
services:
  - mysql

before_script:
  - mysql -e 'create database myapp_test'
  - mysql -e 'show databases;'

script:
  - nosetests -s --with-coverage --cover-package=desc.twinkles
  - pylint --py3k `find . -name \*.py -print | grep -v workflows`

after_success:
  - coveralls
