language: C

install:
  - travis_wait 30 ./setup/travis_install.sh lsst-sims nose pandas pylint
  - ln -sf /home/travis/miniconda/lib/libssl.so.1.0.0 /home/travis/miniconda/lib/libssl.so.10
  - ln -sf /home/travis/miniconda/lib/libcrypto.so.1.0.0 /home/travis/miniconda/lib/libcrypto.so.10
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - pip install coveralls
  - setup lsst_sims
  - eups declare -r . twinkles -t current
  - setup twinkles

cache:
  directories:
  - $HOME/miniconda.tarball
  timeout: 360

services:
  - mysql

before_script:
  - mysql -e 'create database myapp_test'
  - mysql -e 'show databases;'

script:
  - nosetests -s --with-coverage --cover-package=desc.twinkles
  - pylint --py3k `find . -name \*.py -print | grep -v workflows | grep -v conf.py`

after_success:
  - coveralls
  - cd doc
  - pip install -r requirements.txt
  - sphinx-build -b html -a -n -W -d _build/doctree . _build/html
  - ltd-mason-travis --html-dir _build/html

env:
  global:
    - LTD_MASON_BUILD=true  # set to false if using a build matrix, ask @jonathansick
    - LTD_MASON_PRODUCT="twinkles"
    - secure: "ovWt3roijhvicikgEHAEHgF5NuP0Y0zXZYak/Yk66jYQYJk4ZfUmdyP8PObyrivUZafb60G/capBpb44unt6skOfEm24BPtDNPETa+O6QSRQP0STmLCHQPmQPcRfQ0vYj31KVeZnWEG4zCy857ORGhgonJGycaJLCM61V/0NNM4="
    - secure: "FWLPgN9IcOmOES7KOaBAxA2SRh/xAltZJGcc4sZheF0lUUzTgMmrEu6GhIs3ogWfeKxjGDMLiimY7d8+0taqoLSO1hGeCkWoujJ9mrShvBpaRSIzSHDMtqu45LY6/yMuwnpDJdQ1t6WFwUZGKSJ7XZiIbBTVPD7PJNtB4KgYymE="
